# Generated by Django 5.0.1 on 2024-01-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Admin_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('no_of_rooms', models.IntegerField()),
                ('no_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('student_semester', models.IntegerField()),
                ('student_year', models.CharField(max_length=30)),
                ('student_email', models.CharField(max_length=30)),
                ('student_branch', models.CharField(max_length=30)),
                ('student_phone', models.IntegerField()),
                ('student_age', models.IntegerField()),
                ('address_area', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=40)),
                ('address_state', models.CharField(max_length=40)),
                ('student_start_date', models.DateField()),
                ('student_end_date', models.DateField()),
                ('student_application_status', models.CharField(default='Applied', max_length=30)),
                ('hostel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
    ]
