# Generated by Django 5.0.1 on 2024-01-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='no_of_rooms',
            new_name='no_of_vacancy',
        ),
    ]
